[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "forge-std/=lib/forge-std/src/"]
fs_permissions = [{ access = "read", path = "./data" }, { access = "read-write", path = "./data/keytable" }]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 100
fail_on_revert = false

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
